### PR TITLE
Merge experimental Machine-Forth-like language.

### PR DESCRIPTION
**Pull request by sam-falvo**
This is the first and currently most viable Machine Forth-like language and compiler for the RISC-V architecture.  It's still a work-in-progress, but it's complete enough to actually write silly examples and actually have them work!

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Thanks, good reading!

**Comment by sam-falvo** [comment]
Things are just getting started!  :)  Be sure to read the latest commits!

**Comment by larsbrinkhoff** [comment]
I am!  What does BSPL mean?

**Comment by sam-falvo** [comment]
It's short for Bootstrapping Systems Programming Language.  I wrote a short
blog about it here:
http://sam-falvo.github.io/kestrel/2015/09/15/bspl-compiler/

**Pull request merged**
